### ISSUE TITLE
Command-grouping should be part of DRAMPower core

### ISSUE THREAD

**Issue by Sv3n** [tukl-msd/DRAMPower#18]
Moving the command-buffering (i.e. batching x-commands before sending it to the analysis) out of the library-specific code sounds like a good plan, since both the standalone executable and the library could benefit from this functionality, and thus it should probably be shared.

That is, assuming we still need it after we refactor CommandAnalysis.cc.

**Comment by lsteiner-tukl** [comment]
Not relevant any more in v5.0.
