### ISSUE TITLE
commandSorter output has a compiler dependence

### ISSUE THREAD

**Issue by Sv3n** [tukl-msd/DRAMPower#32]
In my experiments with the mac build, I found that some of the tests failed. I tracked down the following issue:
- `CommandAnalysis::getCommands` attempts to insert a PREA command at the start of every trace of commands.
- This command is later sorted together with the other commands by `CommandAnalysis::commandSorter`, competing with other commands that happen at time `t = 0`
- On ubuntu, the PREA command is sorted to the top of the list as expected. On mac, it is not. This causes a trace which starts with an ACT (at `t=0`) to open and then immediately close a bank.
- We do not seem to need the PREA command at the start of the trace. I've updated the tests references which changed as a result. I still need to double check if this is correct.

**Comment by Sv3n** [comment]
What I forgot to mention is that our sorting function is not enforcing an order on the PREA command, so it ends up in a random place (either at position 0 or 1 in the list). This is what I meant by the compiler dependence.

**Comment by lsteiner-tukl** [comment]
Irrelevant in v5.0.
