### ISSUE TITLE
Review clock cycle counters when exiting self-refresh.

### ISSUE THREAD

**Issue by efzulian** [tukl-msd/DRAMPower#40]
The idea here is to review the counters of cock cycles in self-refresh power-up mode for all possible self-refresh exit contexts.

Both scenarios with and without DLL should be considered.

Other counters like "latest_pre_cycle" (which are assigned in the same context) should also be considered in the analysis.

Some code:

```
if (memSpec.memArchSpec.dll == false) {
   spup_cycles     += memSpec.memTimingSpec.XS - spup_pre;
   latest_pre_cycle = max(timestamp, timestamp +
                        memSpec.memTimingSpec.XS - spup_pre -
                        memSpec.memTimingSpec.RP);
} else {
  spup_cycles     += memSpec.memTimingSpec.XSDLL -
                     memSpec.memTimingSpec.RCD - spup_pre;
  latest_pre_cycle = max(timestamp, timestamp +
                     memSpec.memTimingSpec.XSDLL - memSpec.memTimingSpec.RCD -
                     spup_pre - memSpec.memTimingSpec.RP);
}
```

Additionally, there are useful comments in the pull-request #39.

It is also important to evaluate the relevance of these counters (spup_cycles and latest_pre_cycle). It seems that they are used to calculate some energy components which do not make part of the total trace / pattern energy (total_energy).
E.g.:
latest_pre_cycle --> idle_pre_update() --> idlecycles_pre --> energy.idle_energy_pre --> cout

The removal of irrelevant code chunks  / variables (if any) would be beneficial to the code maintainability.

**Comment by efzulian** [comment]
I believe that engy_sref() is intended to return the self-refresh active energy without the background energy.

Some text extracted from Karthik Chandrasekar's PhD thesis, 2.5.4 Self-Refresh Mode Transition:

> The IDD6 current is consumed for the time period spent in the self-refresh mode as defined in the trace (nSR), which excludes the time spent in finishing the explicit auto-refresh (as depicted in Figure 2.13). The auto-refresh consumes IDD5 − IDD3N over one refresh period (nRFC) from the start of the self-refresh. IDD2N current is consumed when exiting the self-refresh state for the nXSDLL exit period.

Briefly, the time spent in self-refresh is broken in three parts:

1. explicit auto-refresh (duration is tRFC, current is IDD5 − IDD3N)
2. self-refresh mode (duration is determined on exit, current is IDD6)
3. self-refresh power up (duration depends on the presence of DLL since it may need a new lock, current is IDD2N)

Furthermore, he explores different situations regarding the arrival time of the self-refresh exit command (the scenarios are also described in the issue #39).

I think you are right: self-refreshes are not counted in **ref_energy**. There is **sref_energy** for that.

**Comment by efzulian** [comment]
About the changes, my vote goes to option 2. Of course I volunteer to help.

In my opinion, the first thing to do would be a clean-up removing everything that is unnecessary reducing the chance that people extend it. I see that you are doing lots of improvements it in the **refact_ca** branch.

**Comment by Sv3n** [comment]
Note to self:
ignore the "SRE" edge, and the little state-bubble it flows into in the state diagram. The general rule that DRAMPower follows when it comes to modeling SREF is:

On SREN:
 * use power-down versions for background currents.
 * Emulate an initial refresh command (use E_ref for the command), but with power-down background currents.
 * If more than RFC cycles pass, go to IDD6 mode.
 * If SRX happens before RFC cycles have passed, switch currents to powered up versions, finish the refresh, and continue as normal after that.
