### ISSUE TITLE
Double check the usage of tRCD when exiting low power modes.

### ISSUE THREAD

**Issue by efzulian** [tukl-msd/DRAMPower#46]
Double check the usage of tRCD (ACT to internal read or write delay time (?)) when exiting low power modes.

Note that this has influence on some variables that may be useless (e.g., latest_act_cycle).

**Comment by Sv3n** [comment]
I've removed the RCD and the RP related entries in 1e767c9af. Now I'm trying to see what to make of `zero_guard(t.XPDLL - t.RCD - t.RP, "t.XPDLL - t.RCD - t.RP")` and `zero_guard(t.XPDLL - (2 * t.RCD), "t.XPDLL - (2 * t.RCD) < 0")`. Both of these warnings trigger:

```
libdrampower-based window example output should match drampower output for DDR2-1066 with the window command trace ...
WARNING: t.XPDLL - t.RCD - t.RP
WARNING: t.XPDLL - (2 * t.RCD) < 0
WARNING: t.XPDLL - t.RCD - t.RP
WARNING: t.XPDLL - (2 * t.RCD) < 0
WARNING: t.XPDLL - t.RCD - t.RP
WARNING: last_pre_cycle is in the future
WARNING: t.XPDLL - t.RCD - t.RP
WARNING: t.XPDLL - (2 * t.RCD) < 0
WARNING: last_pre_cycle is in the future
WARNING: t.XPDLL - t.RCD - t.RP
WARNING: last_pre_cycle is in the future
WARNING: t.XPDLL - (2 * t.RCD) < 0
WARNING: last_pre_cycle is in the future
WARNING: t.XPDLL - t.RCD - t.RP
WARNING: last_pre_cycle is in the future
```
