### ISSUE TITLE
Slow-exit active power-down is not supported by any memory, but we model it anyway.

### ISSUE THREAD

**Issue by Sv3n** [tukl-msd/DRAMPower#48]
I think that in our efforts to be complete, we might have gone too far. We support:

Slow-exit precharged power-down
Fast-exit precharged power-down
Slow-exit active power-down
Fast-exit active power-down

As far as I can tell from the JEDEC / Micron specs, _Slow-exit active power-down_ does not exist in DDR2/3/4 and LPDDR1/2/3. I propose we remove support for the `PDN_S_ACT` command.

**Comment by lsteiner-tukl** [comment]
Resolved in v5.0.
