### ISSUE TITLE
compile Error

### ISSUE THREAD

**Issue by saadahmed1998** [tukl-msd/DRAMPower#53]
When i run the command "make -j4" it gives me this error
g++ -O -W -pedantic-errors -Wextra -Werror -Wformat -Wformat- 
nonliteral -Wpointer-arith -Wcast-align -Wconversion -Wall -Werror -g   
-std=c++0x -MMD -MF src/TraceParser.d -iquote src -o src/TraceParser.o 
-c src/TraceParser.cc
 g++ -O -W -pedantic-errors -Wextra -Werror -Wformat -Wformat- 
nonliteral -Wpointer-arith -Wcast-align -Wall -Werror -g   -std=c++0x 
-MMD -MF src/CmdScheduler.d -iquote src -o src/CmdScheduler.o -c 
src/CmdScheduler.cc
g++ -O -W -pedantic-errors -Wextra -Werror -Wformat -Wformat- 
nonliteral -Wpointer-arith -Wcast-align -Wconversion -Wall -Werror -g   
-std=c++0x -MMD -MF src/cli/drampower.d -iquote src -o 
src/cli/drampower.o -c src/cli/drampower.cc
g++ -O -W -pedantic-errors -Wextra -Werror -Wformat -Wformat- 
nonliteral -Wpointer-arith -Wcast-align -Wconversion -Wall -Werror -g   
-std=c++0x -MMD -MF src/libdrampower/LibDRAMPower.d -iquote src -o 
src/libdrampower/LibDRAMPower.o -c src/libdrampower/LibDRAMPower.cc
In file included from src/CommandAnalysis.h:55:0,
             from src/TraceParser.h:46,
             from src/TraceParser.cc:37:
src/Utils.h:49:1: error: dynamic exception specifications are 
deprecated in C++11 [-Werror=deprecated]
throw(std::runtime_error)
^~~~~
In file included from src/CommandAnalysis.h:55:0,
             from src/libdrampower/LibDRAMPower.h:48,
             from src/libdrampower/LibDRAMPower.cc:42:
src/Utils.h:49:1: error: dynamic exception specifications are 
deprecated in C++11 [-Werror=deprecated]
throw(std::runtime_error)
^~~~~
In file included from src/CmdScheduler.h:47:0,
             from src/CmdScheduler.cc:37:
src/Utils.h:49:1: error: dynamic exception specifications are  
deprecated in C++11 [-Werror=deprecated]
throw(std::runtime_error)
^~~~~
In file included from src/CommandAnalysis.h:55:0,
             from src/MemoryPowerModel.h:49,
             from src/cli/drampower.cc:44:
src/Utils.h:49:1: error: dynamic exception specifications are 
deprecated in C++11 [-Werror=deprecated]
throw(std::runtime_error)
^~~~~
cc1plus: all warnings being treated as errors
Makefile:106: recipe for target 'src/libdrampower/LibDRAMPower.o' 
failed
make: *** [src/libdrampower/LibDRAMPower.o] Error 1
make: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
Makefile:106: recipe for target 'src/cli/drampower.o' failed
make: *** [src/cli/drampower.o] Error 1
cc1plus: all warnings being treated as errors
Makefile:106: recipe for target 'src/TraceParser.o' failed
make: *** [src/TraceParser.o] Error 1
cc1plus: all warnings being treated as errors
Makefile:102: recipe for target 'src/CmdScheduler.o' failed
make: *** [src/CmdScheduler.o] Error 1

Can anybody guide me as to what Mistake i am Making?? Thanks

**Comment by efzulian** [comment]
Please take a look at pull-request #52

**Comment by saadahmed1998** [comment]
@efzulian i am new to these things and did not understand the pull request #52.. can you tell me directly as to what mistake i can be making?

**Comment by efzulian** [comment]
It seems to be an issue with the gcc version (the compiler version). Note the message below:
**deprecated in C++11 [-Werror=deprecated]**
In the patch proposed for pull request #52 the author of the pull request removed a line of code, probably because it compiles without that line. Take a look here:
 https://github.com/tukl-msd/DRAMPower/pull/52/commits/da2ce73c307c9e076d7faaa3946833c9ce74153a
Maybe you can try the same thing as a workaround to compile the library with your compiler.
You can also try to use an older version of gcc (I have no suggestion of specific version to be used, but what is in the documentation).
I hope this helps.
