### ISSUE TITLE
Does a memspec correspond to a chip or a rank?

### ISSUE THREAD

**Issue by lucjaulmes** [tukl-msd/DRAMPower#61]
I see the memspecs each have 8 or 16 bit widths (or 128 for wide IO) and have Gb sizes, so I suppose the spec values are per-chip. Is that assumption correct?

In that case, a couple of questions:
- Should the results just be multiplied by the number of chips (so for example with `x8` chips rank, multiply energy results by 8? Similarly by 9 for an ECC rank?)
- Why is the width limited to multiples of 8, since there are `x4` chips?

Or if this assumption is incorrect:
- does the model not take into account the number of chips? 
- should I specify `64` or `72` respectively as widths in the memspecs for ECC/non-ECC ranks?

Sorry if I missed this information in the documentation somwhere.

**Comment by myzinsky** [comment]
Yes you're fully right. Chip level makes most of sense because in some scenarios we have single devices (e.g. PoP) and in some scenarios we have DIMMs... I think internally we also have `x4` memspecs.

In DRAMSys this is handled automatically. We will add this to the documentation.

**Comment by lucjaulmes** [comment]
When I say x4 chips are not supported, I'm mainly referring to this assert, that prevents memspecs from specifying non-multiple of 8 chips:

https://github.com/tukl-msd/DRAMPower/blob/4903ba80f7016e0b61f5d720f4712ba098f38dbb/src/MemArchitectureSpec.cc#L69-L70

Maybe some code also relies on this assumption being true, further down the line.

**Comment by lsteiner-tukl** [comment]
Memspecs now correspond to complete memory subsystems, including chips, ranks, channels etc.
