### ISSUE TITLE
Cherry-picking from my parallel CMake efforts

### ISSUE THREAD

**Issue by RSpliet** [tukl-msd/DRAMPower#64]
Perhaps somewhat unfortunate, but in [my DRAMPower branch](https://github.com/RSpliet/DRAMPower) I've had CMake build support since 2017. I just spotted that you have adopted CMake yourself, but obviously our CMakeLists.txt files differ. There's a few features in my branch related to CMake that may be interesting to forward-port if you wish. These include:
- Targets for a static library (.a) for both libdrampower and libdrampower_xml, and for the CLI tool,
- Install directives for these libraries, such that CMake projects depending on DRAMPower can link using
`find_package(drampower REQUIRED)`
`link_directories(${drampower_DIR})`
`target_link_libraries([target] drampower)`
- An install directive for the XML files, for which the installation directory can be customised (using ccmake)
- A new method that allows querying the install path of the XML files, such that external projects linking against DRAMPower do not need to hard-code this path when invoking the memspec parser.

Do you think any (or all) of these features are worth forward-porting to upstream?

**Comment by myzinsky** [comment]
Yes indeed, It makes sense to include this.

I will think on a way how to do it.

By the way: We're currently working on a complete DRAMPower and therefore many things might change in the future. One direct change will be that we move from XML to JSON to align with our DRAMSys simulator that will be published also soon on GitHub.

**Comment by RSpliet** [comment]
> Yes indeed, It makes sense to include this.
> 
> I will think on a way how to do it.

Thanks. If there is anything I can be of assistance to, please let me know.

**Comment by lsteiner-tukl** [comment]
v5.0 uses CMake by default.
