### ISSUE TITLE
Operator == for MemCommand ignores command timestamp

### ISSUE THREAD

**Issue by AbhishekBagchi** [tukl-msd/DRAMPower#68]
The definition of operator == for MemCommand ignores the timestamp. So it is possible that the wrong command is matched and acted upon when going over all command list. 
For example. src/CommandAnalysis.cc, at line number 195 does this
```list.erase(find(list.begin(), list.end(), cmd));```
This ends up deleting the first command with the same bank and type as the actual intended deletion target..

**Comment by lsteiner-tukl** [comment]
Resolved in v5.0.
