### ISSUE TITLE
make: g++: Command not found

### ISSUE THREAD

**Issue by explorer1022** [tukl-msd/DRAMPower#70]

**Comment by knox357** [comment]
Could you please switch to the branch "develop"?, which used json based memory specs, which has no dependencies with Xerces XML parser. The XML parser will be deprecated in the future releases of DRAMPower.

**Comment by explorer1022** [comment]
Hello
can you explain more I did not understand because I am a beginner?

**Comment by accio-sunshine** [comment]
Hi,
I used this https://github.com/tukl-msd/DRAMPower/tree/develop path for the 'develop' option and made the modifications.
I have a query -
Can you use the specs generated by DRAMSpec in .json as input?

**Comment by myzinsky** [comment]
@accio-sunshine I think not yet, but it is on our roadmap

@AndreChinazzo

**Comment by accio-sunshine** [comment]
I edited the files in DRAMSpec to generate .json files in an acceptable format for DRAMPower for HMC but I found that not all current and timing data( AL, DQSCK , WR , XP, XPDLL , XS , XSDLL , CL , TAW , RRD , WTR , CKE , CKESR ) can be obtained from DRAMSpec. 

Is there any source for obtaining the parameters for HMC ?

Also, it would be useful to have a similar naming convention between DRAMSpec and DRAMPower with a README for the abbreviations.

**Comment by AndreChinazzo** [comment]
@accio-sunshine you can check [DRAMSpec](https://github.com/tukl-msd/DRAMSpec)'s README for the timings and currents description.

I agree about the naming convention. Best would be to have all DRAMXx tools to agree on that. 
@myzinsky @lsteiner-tukl should DRAMSys be taken as the naming reference?

**Comment by accio-sunshine** [comment]
Thank you for your consideration of the request. Looking forward to exploring DRAMSys!
