### ISSUE TITLE
energy of the memory

### ISSUE THREAD

**Issue by fa19355** [tukl-msd/DRAMPower#73]
Hello

When I increase the clkMhz of the memory from memspecs, I noticed that the energy output is decrease. I think increasing the clkMhz shoud increase the energy.

Why increasing the clkMhz , decrease the energy ? 

![energy](https://user-images.githubusercontent.com/69380353/89709170-707f1880-d975-11ea-82d3-f3039afb0ea4.PNG)
![frequency](https://user-images.githubusercontent.com/69380353/89709171-7117af00-d975-11ea-8ed7-8443cd709d56.PNG)

**Comment by myzinsky** [comment]
To which value you changed the frequency, such that we can reproduce it?

Actually that could be really the case, since your trace is simulating faster, you have less background power and less refreshes.

**Comment by explorer1022** [comment]
I  changed the clkMhz.

**Comment by myzinsky** [comment]
To which value?

I think changing the clock only makes no sense anyway...
