### ISSUE TITLE
plans for new memory models

### ISSUE THREAD

**Issue by jjasoliya** [tukl-msd/DRAMPower#76]
Hi, 
do you guys have any plans to add new memory models like LPDDR4, 4x ?

**Comment by myzinsky** [comment]
Yes, we are currently completely restructuring the code Base to make that happen. Like DRAMSYS also DRAMPower will support these new standards.

**Comment by jjasoliya** [comment]
sorry for my impatience but, is there a timeline on when can we expect this new code base ?

**Comment by myzinsky** [comment]
We are currently figuring out the interface power and memory power for the newest JEDEC standards. The schedule for the new DRAMPower is between Q2 and Q3 of 2021.
