### ISSUE TITLE
How to generate the .trace file?

### ISSUE THREAD

**Issue by buyiweiyi** [tukl-msd/DRAMPower#80]
According to my understanding, DRAMpower can calculate the power of a series commands in .trace file. Then , how can I generate my own .trace file? For example, I want to run a .py file and I want to calculate how much power DRAM costs when running this .py file. Could anyone tell me what should I do？

**Comment by myzinsky** [comment]
I recommend you to use the gem5 simulator, where you run the python file in FS mode. gem5's DRAM controller model has DRAMPower already integrated. 

There are also other solutions: 

You can filter out the memory accesses after the LLC of you program e.g. with PIN and put this e.g. in the DRAMSys simulator, which also has DRAMPower integrated.

You could instrument your python script in some way to filter out the memory accesses. However, this would be just a rough approximation, which does not consider caches etc. But this technique could be helpful to explore the access patterns of accelerators e.g. on an FPGA.

**Comment by buyiweiyi** [comment]
Thanks for your help! I run the python file on the raspberry pi. I will try to filter out the memory accesses or use a simulator.
