### ISSUE TITLE
single bank power/energy simulation

### ISSUE THREAD

**Issue by ivanfang72** [tukl-msd/DRAMPower#82]
Hi, I'm trying to do near memory computing at bank level parallelism and trying to simulate the power and energy of single bank. I've made the command trace to only bank 0. I'm trying to modify the nbrOfBanks to 1 in memspecs and found that there's no difference at the output when it's set to default 8 (I'm using LPDDR3 1600). Is there anything wrong here, or it's not supposed to be use like this? Thanks!

**Comment by myzinsky** [comment]
https://github.com/tukl-msd/DRAMPower/tree/develop

here you can see that there is a bankwise option. 

However, we just finishing a complete reworked DRAMPower which we will also upload soon. 

BR
